
export const ENVIRONMENTAL_SUSTAINABILITY = [
    { l: "Environmental Impact Report", f: "Project → Effect" },
    { l: "Pollution Assessment", f: "Source → Level" },
    { l: "Climate Change Report", f: "Region → Trend" },
    { l: "Conservation Plan", f: "Species → Action" },
    { l: "Biodiversity Survey", f: "Area → Species List" },
    { l: "Sustainability Report", f: "Company → Score" },
    { l: "Carbon Footprint Report", f: "Activity → CO2 Emission" },
    { l: "Renewable Energy Proposal", f: "Source → Output" },
    { l: "Environmental Policy", f: "Topic → Guidelines" },
    { l: "Waste Management Plan", f: "Waste Type → Method" },
    { l: "Recycling Program", f: "Material → Procedure" },
    { l: "Habitat Restoration Plan", f: "Area → Species" },
    { l: "Water Quality Report", f: "Sample → Value" },
    { l: "Air Quality Monitoring", f: "Station → Level" },
    { l: "Soil Analysis Report", f: "Sample → Composition" },
    { l: "Energy Efficiency Plan", f: "System → Savings" },
    { l: "Green Building Certification", f: "Component → Score" },
    { l: "Environmental Audit", f: "Facility → Compliance" },
    { l: "Environmental Risk Assessment", f: "Hazard → Impact" },
    { l: "Ecological Survey", f: "Species → Count" },
    { l: "Wildlife Protection Plan", f: "Species → Strategy" },
    { l: "Climate Adaptation Plan", f: "Risk → Action" },
    { l: "Natural Resource Management Plan", f: "Resource → Usage" },
    { l: "Environmental Education Material", f: "Topic → Activity" },
    { l: "Sustainability Metrics Dashboard", f: "Indicator → Value" },
    { l: "Eco-Friendly Product Plan", f: "Material → Production" },
    { l: "Carbon Reduction Strategy", f: "Activity → CO2 Saved" },
    { l: "Pollution Control Plan", f: "Industry → Regulation" },
    { l: "Environmental Compliance Checklist", f: "Rule → Status" },
    { l: "Energy Consumption Report", f: "Device → Value" },
    { l: "Environmental Policy Memo", f: "Topic → Action" },
    { l: "Environmental Research Proposal", f: "Hypothesis → Method" },
    { l: "Wildlife Monitoring Report", f: "Species → Trend" },
    { l: "Coastal Protection Plan", f: "Area → Measure" },
    { l: "Flood Risk Assessment", f: "Zone → Probability" },
    { l: "Deforestation Report", f: "Area → Impact" },
    { l: "Environmental Awareness Campaign", f: "Topic → Target Audience" },
    { l: "Hazardous Waste Report", f: "Type → Quantity" },
    { l: "Green Transportation Plan", f: "Mode → Efficiency" },
    { l: "Renewable Energy Report", f: "Source → Output" },
    { l: "Climate Policy Review", f: "Measure → Outcome" },
    { l: "Environmental Sustainability Strategy", f: "Goal → Action" },
    { l: "Water Conservation Plan", f: "Area → Method" },
    { l: "Urban Green Space Plan", f: "Location → Feature" },
    { l: "Eco-Tourism Report", f: "Site → Impact" },
    { l: "Wildlife Rehabilitation Plan", f: "Species → Care" },
    { l: "Environmental Monitoring Plan", f: "Parameter → Frequency" },
    { l: "Environmental Legislation Summary", f: "Law → Application" },
    { l: "Energy Audit Report", f: "System → Findings" },
    { l: "Sustainable Agriculture Plan", f: "Crop → Method" },
    { l: "Environmental Data Analysis", f: "Dataset → Insight" },
    { l: "Carbon Accounting Report", f: "Activity → Emission" },
    { l: "Resource Efficiency Plan", f: "Area → Savings" },
    { l: "Wildlife Protection Guidelines", f: "Species → Rule" },
    { l: "Environmental Project Timeline", f: "Task → Milestone" },
    { l: "Renewable Energy Feasibility Study", f: "Location → Output" },
    { l: "Soil Conservation Plan", f: "Field → Measure" },
    { l: "Water Quality Improvement Plan", f: "Source → Action" },
    { l: "Air Pollution Control Strategy", f: "Pollutant → Measure" },
    { l: "Environmental Grant Proposal", f: "Project → Budget" },
    { l: "Climate Resilience Report", f: "Region → Measures" },
    { l: "Ecological Footprint Assessment", f: "Activity → Impact" },
    { l: "Environmental Risk Memo", f: "Issue → Action" },
    { l: "Sustainability Program Evaluation", f: "Initiative → Result" },
    { l: "Natural Disaster Preparedness Plan", f: "Hazard → Procedure" }
];
